# 실행에서 제외할 룰 식별자
disabled_rules:
- line_length
- trailing_whitespace
- function_parameter_count
- file_length
- identifier_name
- function_body_length
- nesting
- cyclomatic_complexity
- void_return
- multiple_closures_with_trailing_closure

# 린트 과정에서 무시할 파일 경로
excluded:
- TheGreatestYourManito-iOS/Application/TheGreatestYourManito_iOSApp.swift
